"""Ajout de la colonne problem_id à Attachment

Revision ID: 55139ca5079b
Revises: d64de985fb2b
Create Date: 2025-07-10 11:09:45.119796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55139ca5079b'
down_revision = 'd64de985fb2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('problem_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'problems', ['problem_id'], ['id'])

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solutions', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index('username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('solutions')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_type')
        batch_op.drop_column('problem_id')

    # ### end Alembic commands ###
