"""Ajout du champ username unique et non nul

Revision ID: d64de985fb2b
Revises: 
Create Date: 2025-07-09 16:25:36.900089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd64de985fb2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_attachments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_column('file_type')

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('solutions')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')
        batch_op.drop_index('username_2')
        batch_op.drop_index('username_3')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', mysql.VARCHAR(length=64), nullable=False))
        batch_op.create_index('username_3', ['username'], unique=True)
        batch_op.create_index('username_2', ['username'], unique=True)
        batch_op.create_index('username', ['username'], unique=True)

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solutions', mysql.TEXT(), nullable=True))

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', mysql.VARCHAR(length=20), nullable=True))

    op.create_table('problem_attachments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('problem_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name='problem_attachments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
